version: '3.8'
services:
  shopping_cart_api:
    image: shopping_cart_tutorial
    container_name: shopping_cart_api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:443"
      - "5000:80"      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate_tutorial.pfx
      - ConnectionStrings__ApplicationDbConnection=Server=shopping_cart_database;Database=shoppingcartdb;User=root;Password=superuser;
    volumes:
      - ./certificate_tutorial.pfx:/https/certificate_tutorial.pfx:ro
    depends_on:
      - shopping_cart_database

  shopping_cart_database:
    image: mysql:8.0
    container_name: "shopping_cart_database"
    volumes:
      - shopping_cart_database_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: shoppingcartdb
      MYSQL_ROOT_PASSWORD: "superuser"
    ports:
      - "3308:3306"

volumes: 
  shopping_cart_database_volume:
   

